"""E15 (lab/NOTES.md entry 38): configs that load other sizes of the SAME open family through the native backend with
identical settings (float16, 768 image-token budget, same prompts and readout), so only the model changes. Written from
configs/default.yaml so they cannot drift from it. Revisions are the ones pinned in MODELS.md.

uv run python tools/make_scaling_configs.py
uv run python -m glance.lab.collect --config configs/scaling_qwen3vl_2b.yaml --bench ladders --split test ...
uv run glance --config configs/scaling_qwen3vl_2b.yaml eval --suite fresh_choice --model vlm
"""
import pathlib

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SIZES = {"2b": ("Qwen/Qwen3-VL-2B-Instruct", "89644892e4d85e24eaac8bacfd4f463576704203"),
         "8b": ("Qwen/Qwen3-VL-8B-Instruct", "0c351dd01ed87e9c1b53cbc748cba10e6187ff3b")}

base = yaml.safe_load((ROOT / "configs/default.yaml").read_text())
for size, (model_id, revision) in SIZES.items():
    cfg = yaml.safe_load(yaml.safe_dump(base))  # deep copy
    cfg["models"]["vlm_tiers"]["lab_scaling"] = {"id": model_id, "revision": revision, "dtype": "float16", "image_token_budget": 768}
    cfg["models"]["tier_override"] = "lab_scaling"
    path = ROOT / f"configs/scaling_qwen3vl_{size}.yaml"
    path.write_text(f"# GENERATED by tools/make_scaling_configs.py from configs/default.yaml: E15, {model_id} through the native backend.\n"
                    + yaml.safe_dump(cfg, sort_keys=False))
    print("wrote", path.relative_to(ROOT))
